### ISSUE TITLE
No updates since last week

### ISSUE THREAD

**Issue by gbasile** [jagalindo/edistribucion#2]
After running successfully for some time, now I'm not receiving updates anymore 😭 

I have found this errors in the logs: 

```
Logger: homeassistant.helpers.entity
Source: custom_components/edistribucion/backend/EdistribucionAPI.py:192
First occurred: 1 February 2021, 21:09:31 (24 occurrences)
Last logged: 2 February 2021, 20:59:05

Update for sensor.eds_power_consumption fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 278, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 482, in async_device_update
    await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/edistribucion/sensor.py", line 51, in update
    meter = edis.get_meter(cups)
  File "/config/custom_components/edistribucion/backend/EdistribucionAPI.py", line 247, in get_meter
    r = self.__command('other.WP_ContadorICP_CTRL.consultarContador=1', post=data)
  File "/config/custom_components/edistribucion/backend/EdistribucionAPI.py", line 134, in __command
    self.__force_login()
  File "/config/custom_components/edistribucion/backend/EdistribucionAPI.py", line 192, in __force_login
    raise EdisError('Unexpected error in loginForm. Cannot continue')
custom_components.edistribucion.backend.EdistribucionAPI.EdisError: Unexpected error in loginForm. Cannot continue
```

and 

```
Logger: homeassistant.helpers.entity
Source: custom_components/edistribucion/backend/EdistribucionAPI.py:192
First occurred: 1 February 2021, 21:09:31 (24 occurrences)
Last logged: 2 February 2021, 20:59:05

Update for sensor.eds_power_consumption fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 278, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 482, in async_device_update
    await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/edistribucion/sensor.py", line 51, in update
    meter = edis.get_meter(cups)
  File "/config/custom_components/edistribucion/backend/EdistribucionAPI.py", line 247, in get_meter
    r = self.__command('other.WP_ContadorICP_CTRL.consultarContador=1', post=data)
  File "/config/custom_components/edistribucion/backend/EdistribucionAPI.py", line 134, in __command
    self.__force_login()
  File "/config/custom_components/edistribucion/backend/EdistribucionAPI.py", line 192, in __force_login
    raise EdisError('Unexpected error in loginForm. Cannot continue')
custom_components.edistribucion.backend.EdistribucionAPI.EdisError: Unexpected error in loginForm. Cannot continue
```

y por cierto, mucha gracias por el trabajo ;) 🍺

**Comment by gbasile** [comment]
Maybe related to this other update here? 

https://github.com/trocotronic/edistribucion/issues/4#issuecomment-788420250

**Comment by jagalindo** [comment]
I've just updated the backend, let me know if this helps

**Comment by bepece1** [comment]
Buenos días,
He instalado la ultima versión con los cambios en el backend y no me funciona.
Hasta el momento con la anterior versión todo me funcionaba bien.
¿a alguien más le ocurre?

Adjunto log:

> Logger: homeassistant.loader
Source: loader.py:802
First occurred: 10:06:47 (2 occurrences)
Last logged: 10:07:03
No 'version' key in the manifest file for custom integration 'edistribucion'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'edistribucion'

Edito: Solucionado actualizando HomeAssistant a la versión actual (2021.4.6)

**Comment by jagalindo** [comment]
Has probado a borrar los ficheros temporales que crea el backend? .session

Por otra parte parece que home assistant indica que hay que añadir un parámetro versión al código. Lo dejo añadido ya para evitar ese warning

**Comment by JJoaquinrl** [comment]
Hola a todos, gran trabajo está integración.
Alguien me podría decir cómo crear un sensor con el dato de totalizador?
Quería crear un timer de 24h y que me dijera lo consumido, no el total del contador que da en el totalizador
Gracias

**Comment by JJoaquinrl** [comment]
Otro asunto...
He visto que realmente el totalizador es la suma de las 3 tarifas del contador, ya que he mirado el contador y es así, sería posible saber esos 3 datos por independiente en vez del total?
Gracias

**Comment by juvenalandres** [comment]
> Otro asunto...
> He visto que realmente el totalizador es la suma de las 3 tarifas del contador, ya que he mirado el contador y es así, sería posible saber esos 3 datos por independiente en vez del total?
> Gracias

Podrías crear un sensor template junto con [https://www.home-assistant.io/integrations/utility_meter/](url).

```sensor:
 - platform: template
    tramos_hora_pvpc:
      friendly_name: "Tramos Horarios PVPC" 
      value_template: >-
        {% set current_hour = strptime(states('sensor.time'), "%H:%M").hour %}
        {% if 0 <= current_hour < 8 %}
          Tarifa Valle
        {% elif 8 <= current_hour < 10 %}
          Tarifa Plana
        {% elif 10 <= current_hour < 14 %}
          Tarifa Punta
        {% elif 14 <= current_hour < 18 %}
          Tarifa Plana
        {% elif 18 <= current_hour < 22 %}
          Tarifa Punta
        {% else %}
          Tarifa Plana
        {% endif %}
```

**Comment by juvenalandres** [comment]
Yo tengo corte intermitentes de datos, como por ejemplo hoy desde las 8 de la mañana. Tiene algo que ver con edistribución?

![image](https://user-images.githubusercontent.com/18738412/120887341-7e7fe300-c5f2-11eb-9bb9-5e52392a6280.png)

**Comment by JJoaquinrl** [comment]
> Yo tengo corte intermitentes de datos, como por ejemplo hoy desde las 8 de la mañana. Tiene algo que ver con edistribución?
> 
> ![image](https://user-images.githubusercontent.com/18738412/120887341-7e7fe300-c5f2-11eb-9bb9-5e52392a6280.png)

Es general, yo lo tengo igual desde la misma hora

**Comment by jagalindo** [comment]
También he estado padeciendo algunos de estos cortes. Parece que el PR de @bvis corrige el problema
