### ISSUE TITLE
Compatibilidad con panel energia home assistant

### ISSUE THREAD

**Issue by yevon** [jagalindo/edistribucion#7]
Buenos días!

Acabo de instalar la integración, aunque de momento creo que no me está funcionando es normal? A parte de eso estaría bien que se integrase con el nuevo panel de energia de home assistsant.

Para ello sólo haria falta que el sensor incluyera estas dos propiedades:

state_class: measurement
last_reset (Fecha del último reinicio del contador del sensor)

Gracias!

**Comment by marc-pujol** [comment]
Buenas tardes, yo la tengo instalada de hace unas semanas y esta ultima semana parece que no funciona o por lo menos no muestra datos de consumo. 

Coincido con @yevon en que estaría muy bien integrarlo en el nuevo panel de energía.

**Comment by halu85** [comment]
Aquí otro al que le funcionaba bastante bien pero de una semana para acá nada de nada.

**Comment by bvis** [comment]
Creo que con los cambios de aquí esto debería volver a funcionar: https://github.com/jagalindo/edistribucion/pull/8

**Comment by bepece1** [comment]
> Buenos días!
> 
> Acabo de instalar la integración, aunque de momento creo que no me está funcionando es normal? A parte de eso estaría bien que se integrase con el nuevo panel de energia de home assistsant.
> 
> Para ello sólo haria falta que el sensor incluyera estas dos propiedades:
> 
> state_class: measurement
> last_reset (Fecha del último reinicio del contador del sensor)
> 
> Gracias!

¿Alguien sabe como incluir en el sensor las 2 propiedades que comenta @yevon?
Estaria genial que fuese compatible con la nueva funcionalidad ("Energia") de HA

**Comment by jagalindo** [comment]
Ahora debería de funcionar con el aporte de @bvis  . No obstante yo también me estoy encontrando con errores en el acceso al contador. Asumo que andan limitando el numero de peticiones.
